# Template for the Ubuntu 22.04 server cloud image
templates:
  - name: "ubuntu-2204-cloudinit-template"
    id: 9001
    memory: 2048
    cpu: 2
    desc: "ubuntu 22.04 server cloudimg-amd64-disk-kvm"
    cloud_init_image:
      name: ubuntu-22.04-server
      url: https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img
      # get the url_checksum below with : curl -sL https://cloud-images.ubuntu.com/releases/22.04/release/SHA256SUMS | grep ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img | awk '{print $1}'
      url_checksum: sha256:3f9f7e6f0d530e1d852588a51b6f61cbbbbe8e13ee5e40781a1b50845d5600a4
      path: /tmp/ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img

ansible_key_pub: "{{ lookup('file', '~/.ssh/id_vm_proxmox_rsa.pub') }}"
root_passwd: '{{ lookup("env", "ssh_key_file") or "rootpasswd" }}'