---
- name: Configure proxmox, Setup terraform permission and Create VM Template
  hosts: proxmox_hosts
  become: true
  roles:
    - role: configure_proxmox # This line imports the "configure_proxmox" role, which is used to configure Proxmox.
      tags:
        - configure_proxmox # This line specifies that this role should be applied when running the playbook with the "configure_proxmox" tag.
  vars_files:
    - .secrets/terraform_permissions_secrets.yml
