---
# tasks file for roles/create-vm-template
- name: Install libguestfs-tools
  ansible.builtin.apt:
    name: libguestfs-tools
    state: present

- name: Check cloud-init image list
  ansible.builtin.command: "qm list"
  register: qm_list
  changed_when: false

- name: Build template
  when: "template_name not in qm_list.stdout"
  block:
    - name: Download cloud image
      ansible.builtin.get_url:
        url: "{{ cloud_image_url }}"
        dest: "{{ cloud_image_path }}"
        checksum: "{{ cloud_image_url_checksum }}"
        mode: "0700"
      changed_when: false
    

    - name: install qemu-guest into cloud image and set root passwd
      ansible.builtin.command: |
        virt-customize -a {{ cloud_image_path }} \
        --root-password password:{{ template_root_passwd }} \
        --install qemu-guest-agent
      changed_when: false

    - name: Create a VM to use as a template
      ansible.builtin.command: |
        qm create {{ template_id }} \
        --memory {{ template_memory }} \
        --core {{ template_cpu }} \
        --name {{ template_name }} \
        --net0 virtio,bridge=vmbr0
        --description test
      changed_when: false

    - name: Import disk image
      ansible.builtin.command: |
        qm importdisk {{ template_id }} {{ cloud_image_path }} local-lvm
      changed_when: false

    - name: Attach disk to vm
      ansible.builtin.command: |
        qm set {{ template_id }} --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-{{ template_id }}-disk-0
      changed_when: false

    - name: Configure boot from the image
      ansible.builtin.command: |
        qm set {{ template_id }} --boot c --bootdisk scsi0
      changed_when: false

    - name: Add cloud-init image as CDROM
      ansible.builtin.command: |
        qm set {{ template_id }} --ide2 local-lvm:cloudinit
      changed_when: false
      
    - name: Attach serial console
      ansible.builtin.command: |
        qm set {{ template_id }} --serial0 socket --vga serial0
      changed_when: false
    
    - name: Enable agent
      ansible.builtin.command: |
        qm set {{ template_id }} --agent enabled=1
      changed_when: false
    
    - name: Create template
      ansible.builtin.command: |
        qm template {{ template_id }}
      changed_when: false
    
    - name: resize disk 2G (default) + 18G to 20G 
      ansible.builtin.command: |
        qm resize {{ template_id }} scsi0 +18G
      changed_when: false