---
# tasks file for roles/join-workers
- name: read join command
  ansible.builtin.debug: msg={{ lookup('file', join_command_location) }}
  register: join_command_local
  
- name: show join command
  ansible.builtin.debug:
    var: join_command_local.msg
    
- name: join agents to cluster
  ansible.builtin.command: "{{ join_command_local.msg }}"