---
- name: Create directory for docker-compose
  ansible.builtin.file:
    path: /opt/portainer/agent/
    state: directory
    owner: root
    group: root
    mode: '0600'

- name: Copy docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/portainer/agent/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd /opt/portainer/agent
    docker compose down -v
  register: portaine_agent_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd  /opt/portainer/agent
    docker compose up -d
  register: portainer_agent_compose_up
  changed_when: true
