---
- hosts: all
  name: Set up Kubernetes components
  become: yes
  pre_tasks:
    - name: Gather service state information as fact data
      ansible.builtin.service_facts:    
    #- name: Print services facts
    #  ansible.builtin.debug:
    #    var: ansible_facts.services
  roles:
    - role: bootstrap-node
      tags:
        - bootstrap-node
    - role: install-runc
      tags:        
        - install-runc
    - role: install-cni-plugins
      tags:        
        - install-cni-plugins
    - role: configure-containerd
      tags:        
        - configure-containerd
    - role: install-cri-tools
      tags:        
        - install-cri-tools
    - role: cfg-kubeadm-kubelet-kubectl
      tags:
        - cfg-kubeadm-kubelet-kubectl

- hosts: control_plan_nodes
  name: Initialize Kubernetes control plane on primary node
  become: yes
  roles:
    - role: init-kubeadm
      tags:
        - init-kubeadm
    - role: kubectl_cheat_sheet
      tags:
        - kubectl_cheat_sheet


- hosts: worker_nodes
  name: join the workers/agents
  become: yes
  roles:
    - role: join-workers
      tags:
        - join-workers
        