---
- name: Check and display the content of /root/.terraform_token
  hosts: proxmox_hosts
  become: true
  tasks:
    - name: Check if /root/.terraform_token exists
      ansible.builtin.stat:
        path: /root/.terraform_token
      register: terraform_token_stat

    - name: Display the content of /root/.terraform_token if it exists
      ansible.builtin.command: cat /root/.terraform_token
      when: terraform_token_stat.stat.exists
      register: terraform_token_content
      changed_when: false

    - name: Show the content of the terraform token file
      ansible.builtin.debug:
        msg: "Terraform Token Content: {{ terraform_token_content.stdout }}"
      when: terraform_token_stat.stat.exists
