---
# tasks file for roles/install-runc
- name: Check if runc exists
  ansible.builtin.stat:
    path: /usr/local/sbin/runc
  register: runc_file

- name: Install runc
  when: not runc_file.stat.exists
  block:
    - name: Download runc
      ansible.builtin.get_url:
        url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
        dest: /usr/local/sbin/runc
        mode: "0755"