---
# tasks file for roles/install-cri-tools
- name: Check if crictl exists
  ansible.builtin.stat:
    path: /usr/local/bin/crictl
  register: crictl_stat

- name: Download and extract crictl
  when: not crictl_stat.stat.exists
  block:
    - name: Download crictl
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-amd64.tar.gz"
        dest: /tmp/crictl.tar.gz
        mode: "0644"

    - name: Extract crictl
      ansible.builtin.unarchive:
        src: /tmp/crictl.tar.gz
        dest: /usr/local/bin/
        remote_src: true