---
- name: Configure proxmox, Setup terraform permission and Create VM Template
  hosts: proxmox_hosts
  become: true
  roles:
    - role: configure
      tags:
        - configure
    - role: manage
      tags:
        - manage
  vars_files:
    - .secrets/config.yml
