---
- name: Create directory for Gitlab Runner
  ansible.builtin.file:
    path: /opt/gitlab-runner
    state: directory
    mode: '0755'

- name: Create configuration directory for GitLab Runner
  ansible.builtin.file:
    path: /opt/gitlab-runner/config
    state: directory
    mode: '0755'

- name: Copy the docker-compose.yml for GitLab Runner from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/gitlab-runner/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Stop and remove existing Docker Compose services
  ansible.builtin.shell: |
    cd /opt/gitlab-runner
    docker compose down -v
  register: gitlab_runner_compose_down
  changed_when: true

- name: Start Docker Compose services
  ansible.builtin.shell: |
    cd /opt/traefik/{{ traefik_version }}
    docker compose up -d
  register: gitlab_runner_compose_up
  changed_when: true
